apps:
  root: 
    ref: apps.index:app
  mounts:
    -
      ref: 'apps.fois'
      path: /streams
      deps:
          datastore: $datastores:master
    -
      ref: apps.config_debugger
      path: /debug
      config:
          scan: data