apps:
  -
    path: /debug
    ref: apps.config_debugger
    config:
        scan: data
  -
    path: /streams
    ref: apps.fois
    plugins:
        -
            ref: bottle.ext.sqlite.Plugin
            config: 
                dbfile: foo.db
  -
    path: /
    ref: apps.index
    type: merge