datastores:
    master:
        ref: bottling.persistence.sqlalchemy_adapter
        config:
            engine:
                dsn: "sqlite:///:memory:"
                echo: False
            plugin:
                keyword: db
                create: False
                commit: True
                use_kwargs: True