logging:
    version: 1
    disable_existing_loggers: False
    formatters:
        verbose:
            format: '%(levelname)s %(asctime)s %(name)s %(process)d %(thread)d %(message)s'
        simple:
            format: '%(levelname)s %(module)s: %(message)s'
    handlers:
        console:
            class: logging.StreamHandler
            formatter: simple
            stream: ext://sys.stdout
    root:
        level: DEBUG
    loggers:
        __main__:
            level: INFO
            handlers: [console]
        apps:
            level: INFO
            handlers: [console]
        bottling:
            level: DEBUG
            handlers: [console]
        sqlalchemy:
            level: INFO
            handlers: [console]