mounts:
  -
    # here we mount the pluggable app `bar` as-is
    'path': '/bar'
    'ref': 'apps.bar'
  -
    # same `bar` app except this time with custom config
    'path': '/other-bar'
    'ref': 'apps.bar'
    'config': 'other-1.yml'