datastores.master.engine:
    create: 
        source: sqlalchemy:create_engine(url, echo=echo)
        args:
            url: "sqlite:///:memory:"
            echo: False
datastores.master.plugin:
    create: 
        source: bottle.ext.sqlalchemy:Plugin(engine, keyword=keyword)
        args:
            engine: 
                $ref: datastores.master.engine
            keyword: db
            create: False
            commit: True
            use_kwargs: True